### PR TITLE
Avoid needlessly deleting WeakMap entries

### PR DESCRIPTION
**Pull request by novemberborn**
Per https://github.com/dojo/shim/issues/6.

The `dojo-shim` dependency seems to be missing in `master` so I assume CI will fail.

### CODE REVIEW

**Comment by kitsonk** [comment]
No, while that was incorrect, CI was still passing, because the Travis script was not looking at the `package.json` to install the peer dependencies.  There is a unit test that is trying to validate the state is deleted once the instance is `.destroyed()` which is no longer the case.  So the unit tests need to be aligned to change behaviour on this PR.

**Comment by novemberborn** [comment]
Updated. Now using a regular `Map` in `createStateful`, since its destruction can be observed.

**Comment by novemberborn** [comment]
Except… that's still not ideal. Yes, destruction can be observed. But it should also be possible to dereference a stateful and have it be garbage collected. Using `Map` prevents that. Pushed another commit which undoes any changes in `createStateful`.

**Comment by kitsonk** [comment]
👍

**Pull request merged**
