### PR TITLE
Refactoring prototype mutation

### LINKED ISSUE #2: Refactor mutations to prototypes
Currently the way compose handles mutating the prototype when constructing the class and mixing in properties is likely not sufficient and needs to be more robust.  For example, it is unlikely that enumerability, configurability and accessor properties will be handled as intended.

Also, it should be refactored to re-use as much of core as possible.

### PR DESCRIPTION
**Pull request by maier49**
Fixes #2

Added a new version of assign that handles getters and setters,
and reorganized code so that prototypes are immutable but instances
are not.

### CODE REVIEW

**Comment by maier49** [comment]
This really has two parts at this point, first is creating a new assign function in compose that handles properties with accessors. For that, I'm not sure if handling accessors is something that core wants to do in assign, so I don't know where this function should ultimately land.

The second part is reorganizing the code so that in all cases the prototypes are immutable but the instances are mutable. If we don't want immutable prototypes then I can update this branch, but we'll still have to make some changes because as master stands any instances created after using extend or mixin have all immutable properties.

**Comment by kitsonk** [comment]
We should have some test cases that specifically try to deal with "exotic" mixin objects to make sure it works...  Something where we have getters/setters, getter only, setter only, non-configurable, non-writable, etc.  See if there are any edge cases we don't expect.

**Comment by maier49** [comment]
I did add an object one that has both a getter and setter, but I can pull
that to its own test case and add some more for those other edge cases you
mention as well.

**Comment by kitsonk** [comment]
DOH! Sorry, [you're right](https://github.com/dojo/compose/pull/12/files#diff-38e5eea62958f9cff1ccde025209b302R180).  I missed it.  Yes, it would be good to have a suite of all the sort of crazy "exotic" scenarios.

**Comment by kitsonk** [comment]
On more thought, do we think that this reworked version of assign should only exist in dojo/compose, or really should we be migrating it to dojo/core?  This does relate to dojo/core#54 which we closed, but I guess is the native Object.assign not handling things as we would like?

**Comment by maier49** [comment]
About `assign` in `core`, its JSDoc comment currently reads:

> Copies the values of all enumerable own properties of one or more source objects to the target object.

In my mind, the value of a property would be what the getter returns as opposed to the getter itself, so it sounds to me at least as if its current behavior is in line with the documentation. The MDN documentation for `Object.assign` also makes it clear that it shouldn't be used for merging new properties into a prototype, so the core implementation is in line with that. 

Maybe `assign` in `compose` should be renamed to avoid confusion? It could also be moved into `core` under the new name if we decide we want that functionality there as well.

**Comment by maier49** [comment]
After talking with @kitsonk some more I've updated the branch so that instead of making all prototypes immutable it simply copies properties and their descriptors as-is from source objects. One reason for this is so that if there is a property which specifically is meant to be non-writable, that information will be carried through to the final instance without having to maintain some kid of record of what the original descriptors of the properties were once they're made non-writable on the prototype.

**Comment by kitsonk** [comment]
:+1: merging... Thanks!!!

**Pull request closed without merging**
